imports:
    - { resource: tables.yml }

services:
    lmdi.multilinks.listener:
        class: lmdi\multilinks\event\listener
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@template'
            - '@user'
            - '%lmdi.multilinks.tables.multilinks%'
        tags:
            - { name: event.listener }

    lmdi.multilinks.multilinks_path_helper:
        class: lmdi\multilinks\core\path_helper
        arguments:
            - '@ext.manager'
            - '@path_helper'
