services:
    lmdi.multilinks.listener:
        class: lmdi\multilinks\event\listener
        arguments:
            - '@user'
            - '@config'
            - '@config_text'
            - '@template'
        tags:
            - { name: event.listener }

    lmdi.multilinks.multilinks_path_helper:
        class: lmdi\multilinks\core\path_helper
        arguments:
            - '@ext.manager'
            - '@path_helper'
