services:
    lmdi.multilinks.listener:
        class: lmdi\multilinks\event\listener
        arguments:
            - '@user'
            - '@config'
            - '@config_text'
            - '@template'
        tags:
            - { name: event.listener }

